// @summary Manages .diligent directory structure with paths and gitignore setup
import { mkdir, stat } from "node:fs/promises";
import { join } from "node:path";

export const DEFAULT_STORAGE_NAMESPACE = "diligent";

export function resolveStorageNamespace(env: NodeJS.ProcessEnv = process.env): string {
  const value = env.DILIGENT_STORAGE_NAMESPACE?.trim().toLowerCase();
  if (!value) return DEFAULT_STORAGE_NAMESPACE;
  if (!/^[a-z0-9-]+$/.test(value)) {
    throw new Error(`Invalid DILIGENT_STORAGE_NAMESPACE: ${value}`);
  }
  return value;
}

export function resolveProjectDirName(env: NodeJS.ProcessEnv = process.env): string {
  return `.${resolveStorageNamespace(env)}`;
}

export interface DiligentPaths {
  root: string;
  sessions: string;
  knowledge: string;
  skills: string;
  images: string;
}

export function resolvePaths(projectRoot: string, env: NodeJS.ProcessEnv = process.env): DiligentPaths {
  const root = join(projectRoot, resolveProjectDirName(env));
  return {
    root,
    sessions: join(root, "sessions"),
    knowledge: join(root, "knowledge"),
    skills: join(root, "skills"),
    images: join(root, "images"),
  };
}

const GITIGNORE_CONTENT = `# Auto-generated by diligent
# Sessions and knowledge are machine-local, not version-controlled
sessions/
knowledge/
images/
logs/
`;

async function ensureDirectory(path: string): Promise<void> {
  const existing = await stat(path).catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return null;
    throw error;
  });

  if (existing) {
    if (existing.isDirectory()) return;
    throw new Error(`Expected directory but found a file: ${path}`);
  }

  await mkdir(path, { recursive: true });
}

export async function ensureDiligentDir(
  projectRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<DiligentPaths> {
  const paths = resolvePaths(projectRoot, env);
  await ensureDirectory(paths.sessions);
  await ensureDirectory(paths.knowledge);
  await ensureDirectory(paths.skills);
  await ensureDirectory(paths.images);

  const gitignorePath = join(paths.root, ".gitignore");
  const file = Bun.file(gitignorePath);
  if (!(await file.exists())) {
    await Bun.write(gitignorePath, GITIGNORE_CONTENT);
  }

  return paths;
}
