// @summary Anthropic-owned model-card definitions
import { defineProviderModels, NATIVE_PROVIDER_THINKING_EFFORTS } from "../../model-card";

export const ANTHROPIC_MODELS = defineProviderModels("anthropic", [
  {
    modelId: "claude-opus-4-8",
    display: "Claude Opus 4.8",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    inputCostPer1M: 5,
    outputCostPer1M: 25,
    cacheReadCostPer1M: 0.5,
    cacheWriteCostPer1M: 6.25,
    supportsThinking: true,
    supportedEfforts: NATIVE_PROVIDER_THINKING_EFFORTS,
    supportsVision: true,
    supportsAdaptiveThinking: true,
    supportsXhighEffort: true,
    aliases: ["claude-opus", "opus", "opus-4-8"],
  },
  {
    modelId: "claude-fable-5",
    display: "Claude Fable 5",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    inputCostPer1M: 10,
    outputCostPer1M: 50,
    cacheReadCostPer1M: 1,
    cacheWriteCostPer1M: 12.5,
    supportsThinking: true,
    supportedEfforts: NATIVE_PROVIDER_THINKING_EFFORTS,
    supportsVision: true,
    supportsAdaptiveThinking: true,
    supportsXhighEffort: true,
    aliases: ["fable", "fable-5"],
  },
  {
    modelId: "claude-sonnet-5",
    display: "Claude Sonnet 5",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    cacheReadCostPer1M: 0.3,
    cacheWriteCostPer1M: 3.75,
    supportsThinking: true,
    supportedEfforts: NATIVE_PROVIDER_THINKING_EFFORTS,
    supportsVision: true,
    supportsAdaptiveThinking: true,
    supportsXhighEffort: true,
    aliases: ["sonnet-5"],
  },
  {
    modelId: "claude-sonnet-4-6",
    display: "Claude Sonnet 4.6",
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    cacheReadCostPer1M: 0.3,
    cacheWriteCostPer1M: 3.75,
    supportsThinking: true,
    supportedEfforts: NATIVE_PROVIDER_THINKING_EFFORTS,
    supportsVision: true,
    supportsAdaptiveThinking: true,
    aliases: ["claude-sonnet", "sonnet", "sonnet-4-6"],
  },
  {
    modelId: "claude-haiku-4-5-20251001",
    display: "Claude Haiku 4.5",
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    inputCostPer1M: 1,
    outputCostPer1M: 5,
    cacheReadCostPer1M: 0.1,
    cacheWriteCostPer1M: 1.25,
    supportsThinking: true,
    supportedEfforts: NATIVE_PROVIDER_THINKING_EFFORTS,
    supportsVision: true,
    thinkingBudgets: { low: 1_024, medium: 3_000, high: 8_000, max: 16_000 },
    aliases: ["claude-haiku", "haiku", "claude-haiku-4-5"],
  },
]);
